local Sprites = {
    WINDOW_BACKGROUND = id.Sprite.RS3_MODAL_WINDOW_CONTENT_TILE,
    CLOSE = id.Sprite.RS3_BTN_MODAL_WINDOW_1_CLOSE_NML,
    CLOSE_ACTIVE = id.Sprite.RS3_BTN_MODAL_WINDOW_1_CLOSE_OVR,
    TITLEBAR_RIGHT = id.Sprite.RS3_MODAL_WINDOW_1_CLOSE_CORNER,
    TITLEBAR_LEFT = id.Sprite.RS3_MODAL_WINDOW_1_TITLE_CORNER,
    TITLEBAR_CENTRE = id.Sprite.RS3_MODAL_WINDOW_1_TITLE_END,
    TITLEBAR_CENTRE_RIGHT = id.Sprite.RS3_MODAL_WINDOW_1_TOP_TILE,
    TITLEBAR_CENTRE_LEFT = id.Sprite.RS3_MODAL_WINDOW_1_TITLE_TILE,
    BORDER_LEFT = id.Sprite.RS3_MODAL_WINDOW_1_SIDE_TILE,
    BORDER_BOTTOM = id.Sprite.RS3_MODAL_WINDOW_1_BOTTOM_TILE,
    BORDER_CORNER = id.Sprite.RS3_MODAL_WINDOW_1_BOTTOM_CORNER,
    SCROLL_ARROW_UP = id.Sprite.SCROLLBAR_V2_0,
    SCROLL_ARROW_DOWN = id.Sprite.SCROLLBAR_V2_1,
    SCROLL_TRACK_TOP = id.Sprite.SCROLLBAR_DRAGGER_V2_3,
    SCROLL_TRACK_CENTRE = id.Sprite.SCROLLBAR_DRAGGER_V2_3,
    SCROLL_TRACK_BOTTOM = id.Sprite.SCROLLBAR_DRAGGER_V2_3,
    SCROLL_THUMB_TOP = id.Sprite.SCROLLBAR_DRAGGER_V2_0,
    SCROLL_THUMB_CENTRE = id.Sprite.SCROLLBAR_DRAGGER_V2_1,
    SCROLL_THUMB_BOTTOM = id.Sprite.SCROLLBAR_DRAGGER_V2_2,
    LOADING_SPINNER_FRAMES = {
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_0,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_1,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_2,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_3,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_4,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_5,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_6,
        id.Sprite.RS3_LOGIN_THROBBER_LARGE_7,
    },
    BIG_SPINNER_BACKDROP = id.Sprite.RS3_LOADING_SPINNER_PARENT_BACKING,
    BIG_SPINNER_ROTATING = id.Sprite.RS3_LOADING_SPINNER_CHILD,
    SLIDER = {
        backingEnd = id.Sprite.RS3_SLIDER_BAR_BACKING_END,
        backingTile = id.Sprite.RS3_SLIDER_BAR_BACKING_TILE,
        barEnd = id.Sprite.RS3_SLIDER_BAR_END,
        barTile = id.Sprite.RS3_SLIDER_BAR_TILE,
        thumb = {
            normal = id.Sprite.RS3_BTN_ADJUST_SLIDER_0,
            hovered = id.Sprite.RS3_BTN_ADJUST_SLIDER_1,
            pressed = id.Sprite.RS3_BTN_ADJUST_SLIDER_2,
            disabled = id.Sprite.RS3_BTN_ADJUST_SLIDER_3,
        },
        decrease = {
            normal = id.Sprite.RS3_BTN_DECREASE_ACTIVE,
            hovered = id.Sprite.RS3_BTN_DECREASE_OVER,
            pressed = id.Sprite.RS3_BTN_DECREASE_DOWN,
            disabled = id.Sprite.RS3_BTN_DECREASE_DISABLED,
        },
        increase = {
            normal = id.Sprite.RS3_BTN_INCREASE_ACTIVE,
            hovered = id.Sprite.RS3_BTN_INCREASE_OVER,
            pressed = id.Sprite.RS3_BTN_INCREASE_DOWN,
            disabled = id.Sprite.RS3_BTN_INCREASE_DISABLED,
        },
    },
    RIBBON_BUTTON_DISABLED = id.Sprite.RS3_BTN_MENU_7_4,
    RIBBON_BUTTON_NEUTRAL = id.Sprite.RS3_BTN_MENU_7_2,
    RIBBON_BUTTON_HOVERED = id.Sprite.RS3_BTN_MENU_7_1,
    RIBBON_BUTTON_ACTIVE = id.Sprite.RS3_BTN_MENU_7_3,
    CONTENT_FRAME = {
        topLeft = id.Sprite.RS3_CONTENT_FRAME_0,
        top = id.Sprite.RS3_CONTENT_FRAME_1,
        topRight = id.Sprite.RS3_CONTENT_FRAME_2,
        left = id.Sprite.RS3_CONTENT_FRAME_3,
        centre = id.Sprite.RS3_CONTENT_FRAME_4,
        right = id.Sprite.RS3_CONTENT_FRAME_5,
        bottomLeft = id.Sprite.RS3_CONTENT_FRAME_6,
        bottom = id.Sprite.RS3_CONTENT_FRAME_7,
        bottomRight = id.Sprite.RS3_CONTENT_FRAME_8,
    },
    HUD_WINDOW = {
        cornerTop = id.Sprite.RS3_HUD_WINDOW_CORNER_TOP,
        cornerBottom = id.Sprite.RS3_HUD_WINDOW_CORNER_BOTTOM,
        top = id.Sprite.RS3_HUD_WINDOW_TOP_TILE,
        bottom = id.Sprite.RS3_HUD_WINDOW_BOTTOM_TILE,
        side = id.Sprite.RS3_HUD_WINDOW_SIDE_TILE,
        content = id.Sprite.RS3_HUD_WINDOW_CONTENT_TILE,
    },
    ANCHORED_TOOLTIP = {
        border = {
            topLeft = id.Sprite.RS3_TOOLTIP_BORDER_0,
            top = id.Sprite.RS3_TOOLTIP_BORDER_1,
            side = id.Sprite.RS3_TOOLTIP_BORDER_2,
            bottomLeft = id.Sprite.RS3_TOOLTIP_BORDER_4,
            bottom = id.Sprite.RS3_TOOLTIP_BORDER_5,
        },
    },
    PANEL_POPOUT_BUTTON = { neutral = id.Sprite.RS3_BTN_MINIMISE_16PX_3, hovered = id.Sprite.RS3_BTN_MINIMISE_16PX_4, mousedown = id.Sprite.RS3_BTN_MINIMISE_16PX_5 },
    PANEL_DOCK_BUTTON = { neutral = id.Sprite.RS3_BTN_MINIMISE_16PX_0, hovered = id.Sprite.RS3_BTN_MINIMISE_16PX_1, mousedown = id.Sprite.RS3_BTN_MINIMISE_16PX_2 },
    ITEM_SLOT_BACKGROUND = id.Sprite.RS3_ICON_SLOT_40PX_0,
    ITEM_GRID_BACKGROUND = id.Sprite.RS3_ICON_SLOT_40PX_1,
    ITEM_GRID_DROP_TARGET = id.Sprite.RS3_ICON_SLOT_ITEM_PREMIUM_4,
    DIVIDER = id.Sprite.RS3_PARENT_FRAME_TOP_TILE,
    ICON_TAB = { inactive = id.Sprite.BANK_TABS_HORIZONTAL_0, hovered = id.Sprite.BANK_TABS_HORIZONTAL_2, active = id.Sprite.BANK_TABS_HORIZONTAL_1, disabled = id.Sprite.BANK_TABS_HORIZONTAL_3 },
    TEXT_TAB = {
        disabled = { left = id.Sprite.RS3_PARENT_TAB_LOCKED_LEFT, middle = id.Sprite.RS3_PARENT_TAB_LOCKED_TILE, right = id.Sprite.RS3_PARENT_TAB_LOCKED_RIGHT },
        inactive = { left = id.Sprite.RS3_PARENT_TAB_UNSELECTED_LEFT, middle = id.Sprite.RS3_PARENT_TAB_UNSELECTED_TILE, right = id.Sprite.RS3_PARENT_TAB_UNSELECTED_RIGHT },
        active = { left = id.Sprite.RS3_PARENT_TAB_CURRENT_LEFT, middle = id.Sprite.RS3_PARENT_TAB_CURRENT_TILE, right = id.Sprite.RS3_PARENT_TAB_CURRENT_RIGHT },
    },
}

Sprites.SIMPLE_BUTTON = {
    disabled = {
        topRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_38, topLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_36, top = id.Sprite.RS3_BTN_ICON_RESIZABLE_37,
        left = id.Sprite.RS3_BTN_ICON_RESIZABLE_39, centre = id.Sprite.RS3_BTN_ICON_RESIZABLE_40, right = id.Sprite.RS3_BTN_ICON_RESIZABLE_41,
        bottomLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_42, bottom = id.Sprite.RS3_BTN_ICON_RESIZABLE_43, bottomRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_44,
    },
    neutral = {
        topRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_20, topLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_18, top = id.Sprite.RS3_BTN_ICON_RESIZABLE_19,
        left = id.Sprite.RS3_BTN_ICON_RESIZABLE_21, centre = id.Sprite.RS3_BTN_ICON_RESIZABLE_22, right = id.Sprite.RS3_BTN_ICON_RESIZABLE_23,
        bottomLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_24, bottom = id.Sprite.RS3_BTN_ICON_RESIZABLE_25, bottomRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_26,
    },
    hovered = {
        topRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_11, topLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_9, top = id.Sprite.RS3_BTN_ICON_RESIZABLE_10,
        left = id.Sprite.RS3_BTN_ICON_RESIZABLE_12, centre = id.Sprite.RS3_BTN_ICON_RESIZABLE_13, right = id.Sprite.RS3_BTN_ICON_RESIZABLE_14,
        bottomLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_15, bottom = id.Sprite.RS3_BTN_ICON_RESIZABLE_16, bottomRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_17,
    },
    active = {
        topRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_29, topLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_27, top = id.Sprite.RS3_BTN_ICON_RESIZABLE_28,
        left = id.Sprite.RS3_BTN_ICON_RESIZABLE_30, centre = id.Sprite.RS3_BTN_ICON_RESIZABLE_31, right = id.Sprite.RS3_BTN_ICON_RESIZABLE_32,
        bottomLeft = id.Sprite.RS3_BTN_ICON_RESIZABLE_33, bottom = id.Sprite.RS3_BTN_ICON_RESIZABLE_34, bottomRight = id.Sprite.RS3_BTN_ICON_RESIZABLE_35,
    },
}

Sprites.COLLAPSE_BUTTON = {
    disabled = { left = id.Sprite.RS3_BTN_ACCORDION_18, middle = id.Sprite.RS3_BTN_ACCORDION_19, right = id.Sprite.RS3_BTN_ACCORDION_20 },
    neutral = { left = id.Sprite.RS3_BTN_ACCORDION_6, middle = id.Sprite.RS3_BTN_ACCORDION_7, right = id.Sprite.RS3_BTN_ACCORDION_8 },
    hovered = { left = id.Sprite.RS3_BTN_ACCORDION_3, middle = id.Sprite.RS3_BTN_ACCORDION_4, right = id.Sprite.RS3_BTN_ACCORDION_5 },
    active = { left = id.Sprite.RS3_BTN_ACCORDION_12, middle = id.Sprite.RS3_BTN_ACCORDION_13, right = id.Sprite.RS3_BTN_ACCORDION_14 },
}

Sprites.FANCY_BUTTON = {
    positive = {
        normal = { left = id.Sprite.RS3_BTN_MAIN_POSITIVE_0, middle = id.Sprite.RS3_BTN_MAIN_POSITIVE_1, right = id.Sprite.RS3_BTN_MAIN_POSITIVE_2 },
        hovered = { left = id.Sprite.RS3_BTN_MAIN_POSITIVE_3, middle = id.Sprite.RS3_BTN_MAIN_POSITIVE_4, right = id.Sprite.RS3_BTN_MAIN_POSITIVE_5 },
        pressed = { left = id.Sprite.RS3_BTN_MAIN_POSITIVE_6, middle = id.Sprite.RS3_BTN_MAIN_POSITIVE_7, right = id.Sprite.RS3_BTN_MAIN_POSITIVE_8 },
        disabled = { left = id.Sprite.RS3_BTN_MAIN_POSITIVE_12, middle = id.Sprite.RS3_BTN_MAIN_POSITIVE_13, right = id.Sprite.RS3_BTN_MAIN_POSITIVE_14 },
    },
    neutral = {
        normal = { left = id.Sprite.RS3_BTN_MAIN_NEUTRAL_0, middle = id.Sprite.RS3_BTN_MAIN_NEUTRAL_1, right = id.Sprite.RS3_BTN_MAIN_NEUTRAL_2 },
        hovered = { left = id.Sprite.RS3_BTN_MAIN_NEUTRAL_3, middle = id.Sprite.RS3_BTN_MAIN_NEUTRAL_4, right = id.Sprite.RS3_BTN_MAIN_NEUTRAL_5 },
        pressed = { left = id.Sprite.RS3_BTN_MAIN_NEUTRAL_6, middle = id.Sprite.RS3_BTN_MAIN_NEUTRAL_7, right = id.Sprite.RS3_BTN_MAIN_NEUTRAL_8 },
        disabled = { left = id.Sprite.RS3_BTN_MAIN_NEUTRAL_12, middle = id.Sprite.RS3_BTN_MAIN_NEUTRAL_13, right = id.Sprite.RS3_BTN_MAIN_NEUTRAL_14 },
    },
    negative = {
        normal = { left = id.Sprite.RS3_BTN_MAIN_NEGATIVE_0, middle = id.Sprite.RS3_BTN_MAIN_NEGATIVE_1, right = id.Sprite.RS3_BTN_MAIN_NEGATIVE_2 },
        hovered = { left = id.Sprite.RS3_BTN_MAIN_NEGATIVE_3, middle = id.Sprite.RS3_BTN_MAIN_NEGATIVE_4, right = id.Sprite.RS3_BTN_MAIN_NEGATIVE_5 },
        pressed = { left = id.Sprite.RS3_BTN_MAIN_NEGATIVE_6, middle = id.Sprite.RS3_BTN_MAIN_NEGATIVE_7, right = id.Sprite.RS3_BTN_MAIN_NEGATIVE_8 },
        disabled = { left = id.Sprite.RS3_BTN_MAIN_NEGATIVE_12, middle = id.Sprite.RS3_BTN_MAIN_NEGATIVE_13, right = id.Sprite.RS3_BTN_MAIN_NEGATIVE_14 },
    },
}

Sprites.RADIO_BUTTON = {
    empty = id.Sprite.RS3_BTN_CHECKBOX_SMALL_0,
    emptyHovered = id.Sprite.RS3_BTN_CHECKBOX_SMALL_1,
    selected = id.Sprite.RS3_BTN_CHECKBOX_SMALL_4,
    selectedHovered = id.Sprite.RS3_BTN_CHECKBOX_SMALL_5,
}

Sprites.CHECKBOX_BUTTON = {
    empty = id.Sprite.RS3_BTN_CHECKBOX_SMALL_0,
    emptyHovered = id.Sprite.RS3_BTN_CHECKBOX_SMALL_1,
    selected = id.Sprite.RS3_BTN_CHECKBOX_SMALL_2,
    selectedHovered = id.Sprite.RS3_BTN_CHECKBOX_SMALL_2,
}

Sprites.SPRITE_BUTTONS = {
    MENU = { disabled = id.Sprite.RS3_ICON_ACTION_16PX_4, neutral = id.Sprite.RS3_ICON_ACTION_16PX_2, active = id.Sprite.RS3_ICON_ACTION_16PX_3 },
    FILTER = { disabled = id.Sprite.RS3_ICON_FILTER_16PX_4, neutral = id.Sprite.RS3_ICON_FILTER_16PX_2, active = id.Sprite.RS3_ICON_FILTER_16PX_3 },
    INFO = { disabled = id.Sprite.RS3_ICON_INFO_21PX_4, neutral = id.Sprite.RS3_ICON_INFO_21PX_2, active = id.Sprite.RS3_ICON_INFO_21PX_3 },
    SETTINGS = { disabled = id.Sprite.RS3_ICON_SETTINGS_30PX_4, neutral = id.Sprite.RS3_ICON_SETTINGS_30PX_2, active = id.Sprite.RS3_ICON_SETTINGS_30PX_0 },
    PAUSE = { disabled = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_8, neutral = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_6, active = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_7 },
    STOP = { disabled = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_5, neutral = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_3, active = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_4 },
    PLAY = { disabled = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_2, neutral = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_0, active = id.Sprite.RS3_ICON_STOPWATCH_CONTROLS_1 },
    UNDO = { disabled = id.Sprite.RS3_ICON_STOPWATCH_RESET_2, neutral = id.Sprite.RS3_ICON_STOPWATCH_RESET_0, active = id.Sprite.RS3_ICON_STOPWATCH_RESET_1 },
    REFRESH = { disabled = id.Sprite.RS3_ICON_LOBBY_REFRESH_2, neutral = id.Sprite.RS3_ICON_LOBBY_REFRESH_0, active = id.Sprite.RS3_ICON_LOBBY_REFRESH_1 },
    BACK = { disabled = id.Sprite.RS3_ICON_BACK_43PX_4, neutral = id.Sprite.RS3_ICON_BACK_43PX_2, active = id.Sprite.RS3_ICON_BACK_43PX_1 },
    PIN = { disabled = id.Sprite.RS3_ICON_PINNED_24PX_4, neutral = id.Sprite.RS3_ICON_PINNED_24PX_2, active = id.Sprite.RS3_ICON_PINNED_24PX_3 },
    ERASER = { disabled = id.Sprite.RS3_ICON_CLEAR_16PX_4, neutral = id.Sprite.RS3_ICON_CLEAR_16PX_2, active = id.Sprite.RS3_ICON_CLEAR_16PX_3 },
    CROSS = { disabled = id.Sprite.RS3_AUDIO_OPTION_ICONS_15, neutral = id.Sprite.RS3_AUDIO_OPTION_ICONS_7, active = id.Sprite.RS3_AUDIO_OPTION_ICONS_11 },
    AUDIO = { disabled = id.Sprite.RS3_AUDIO_OPTION_ICONS_13, neutral = id.Sprite.RS3_AUDIO_OPTION_ICONS_5, active = id.Sprite.RS3_AUDIO_OPTION_ICONS_9 },
    PENCIL = { disabled = id.Sprite.RS3_ICON_EDIT_23PX_2, neutral = id.Sprite.RS3_ICON_EDIT_23PX_0, active = id.Sprite.RS3_ICON_EDIT_23PX_1 },
    EYE = { disabled = id.Sprite.RS3_ICON_WARDROBE_EFFECTS_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_EFFECTS_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_EFFECTS_24PX_3 },
    HIDE = { disabled = id.Sprite.RS3_ICON_HIDE_16PX_4, neutral = id.Sprite.RS3_ICON_HIDE_16PX_0, active = id.Sprite.RS3_ICON_HIDE_16PX_1 },
    STAR = { disabled = id.Sprite.RAND_SPEEDRUN_STAR_SILVER_0, neutral = id.Sprite.RAND_SPEEDRUN_STAR_BRONZE_0, active = id.Sprite.RAND_SPEEDRUN_STAR_GOLD_0 },
    LIST_LAYOUT = { disabled = id.Sprite.RS3_ICON_WARDROBE_VIEW_LIST_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_VIEW_LIST_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_VIEW_LIST_24PX_3 },
    GRID_LAYOUT = { disabled = id.Sprite.RS3_ICON_WARDROBE_VIEW_GRID_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_VIEW_GRID_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_VIEW_GRID_24PX_3 },
    CAPE = { disabled = id.Sprite.RS3_ICON_WARDROBE_CAPE_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_CAPE_24PX_3, active = id.Sprite.RS3_ICON_WARDROBE_CAPE_24PX_2 },
    SHIELD = { disabled = id.Sprite.RS3_ICON_WARDROBE_SECONDARY_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_SECONDARY_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_SECONDARY_24PX_3 },
    BODY = { disabled = id.Sprite.RS3_ICON_WARDROBE_TORSO_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_TORSO_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_TORSO_24PX_3 },
    AMULET = { disabled = id.Sprite.RS3_ICON_WARDROBE_NECKLACE_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_NECKLACE_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_NECKLACE_24PX_3 },
    LEGS = { disabled = id.Sprite.RS3_ICON_WARDROBE_LEGS_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_LEGS_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_LEGS_24PX_3 },
    BOOT = { disabled = id.Sprite.RS3_ICON_WARDROBE_FEET_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_FEET_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_FEET_24PX_3 },
    OUTFIT = { disabled = id.Sprite.RS3_ICON_WARDROBE_FULL_OUTFIT_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_FULL_OUTFIT_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_FULL_OUTFIT_24PX_1 },
    HAND = { disabled = id.Sprite.RS3_ICON_WARDROBE_HANDS_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_HANDS_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_HANDS_24PX_3 },
    KEEPSAKE = { disabled = id.Sprite.RS3_ICON_WARDROBE_KEEPSAKE_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_KEEPSAKE_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_KEEPSAKE_24PX_3 },
    PYRAMID = { disabled = id.Sprite.RS3_ICON_WARDROBE_SOURCE_24PX_4, neutral = id.Sprite.RS3_ICON_WARDROBE_SOURCE_24PX_2, active = id.Sprite.RS3_ICON_WARDROBE_SOURCE_24PX_3 },
    SPECIAL = { disabled = id.Sprite.WARDROBE_ICON_NEW_16PX_4, neutral = id.Sprite.WARDROBE_ICON_NEW_16PX_2, active = id.Sprite.WARDROBE_ICON_NEW_16PX_1 },
    PLUS = { disabled = id.Sprite.RS3_ICON_PURCHASE_MORE_2, neutral = id.Sprite.RS3_ICON_PURCHASE_MORE_0, active = id.Sprite.RS3_ICON_PURCHASE_MORE_1 },
    GRAPH = { disabled = id.Sprite.RS3_ICON_MENU_RUNEMETRICS_METRICS_2, neutral = id.Sprite.RS3_ICON_MENU_RUNEMETRICS_METRICS_0, active = id.Sprite.RS3_ICON_MENU_RUNEMETRICS_METRICS_1 },
    IMPORT = { disabled = id.Sprite.RS3_ICON_RUNEMETRICS_NEW_4, neutral = id.Sprite.RS3_ICON_RUNEMETRICS_NEW_2, active = id.Sprite.RS3_ICON_RUNEMETRICS_NEW_3 },
    EXPORT = { disabled = id.Sprite.RS3_ICON_EXTERNAL_LINK_24PX_4, neutral = id.Sprite.RS3_ICON_EXTERNAL_LINK_24PX_2, active = id.Sprite.RS3_ICON_EXTERNAL_LINK_24PX_3 },
    LADDER_UP = { disabled = id.Sprite.RS3_ICON_DIRECTION_ASCEND_32PX_4, neutral = id.Sprite.RS3_ICON_DIRECTION_ASCEND_32PX_2, active = id.Sprite.RS3_ICON_DIRECTION_ASCEND_32PX_3 },
    LADDER_DOWN = { disabled = id.Sprite.RS3_ICON_DIRECTION_DESCEND_32PX_4, neutral = id.Sprite.RS3_ICON_DIRECTION_DESCEND_32PX_2, active = id.Sprite.RS3_ICON_DIRECTION_DESCEND_32PX_3 },
    ARROW_UP = { disabled = id.Sprite.RS3_ICON_DIRECTION_UP_32PX_4, neutral = id.Sprite.RS3_ICON_DIRECTION_UP_32PX_2, active = id.Sprite.RS3_ICON_DIRECTION_UP_32PX_3 },
    ARROW_RIGHT = { disabled = id.Sprite.RS3_ICON_DIRECTION_RIGHT_32PX_4, neutral = id.Sprite.RS3_ICON_DIRECTION_RIGHT_32PX_2, active = id.Sprite.RS3_ICON_DIRECTION_RIGHT_32PX_3 },
    ARROW_LEFT = { disabled = id.Sprite.RS3_ICON_DIRECTION_LEFT_32PX_4, neutral = id.Sprite.RS3_ICON_DIRECTION_LEFT_32PX_2, active = id.Sprite.RS3_ICON_DIRECTION_LEFT_32PX_3 },
    ARROW_DOWN = { disabled = id.Sprite.RS3_ICON_DIRECTION_DOWN_32PX_4, neutral = id.Sprite.RS3_ICON_DIRECTION_DOWN_32PX_2, active = id.Sprite.RS3_ICON_DIRECTION_DOWN_32PX_3 },
    SEARCH = { disabled = id.Sprite.TRH_ICON_SEARCH_QUERY_2, neutral = id.Sprite.TRH_ICON_SEARCH_QUERY_0, active = id.Sprite.TRH_ICON_SEARCH_QUERY_1 },
    CHAT = { disabled = id.Sprite.CHAT_V2_SETTINGS_OFF_2, neutral = id.Sprite.CHAT_V2_SETTINGS_ON_2, active = id.Sprite.CHAT_V2_SETTINGS_OVER_2 },
    DIAMOND = { disabled = id.Sprite.CHAT_V2_SETTINGS_OFF_0, neutral = id.Sprite.CHAT_V2_SETTINGS_ON_0, active = id.Sprite.CHAT_V2_SETTINGS_OVER_0 },
    SWAP = { disabled = id.Sprite.CHAT_V2_SETTINGS_OFF_8, neutral = id.Sprite.CHAT_V2_SETTINGS_ON_8, active = id.Sprite.CHAT_V2_SETTINGS_OVER_8 },
    BROADCAST = { disabled = id.Sprite.RS3_CHAT_FILTER_BROADCAST, neutral = id.Sprite.CHAT_V2_FILTERS_ON_9, active = id.Sprite.CHAT_V2_FILTERS_OVER_9 },
    LOCK = {
        disabled = id.Sprite.HUD_COMBAT_BTN_UNLOCKED,
        disabledHovered = id.Sprite.HUD_COMBAT_BTN_UNLOCKED_OVER,
        neutral = id.Sprite.HUD_COMBAT_BTN_LOCKED,
        active = id.Sprite.HUD_COMBAT_BTN_LOCKED_OVER,
    },
    TRASH = { neutral = id.Sprite.HUD_COMBAT_BTN_BIN, active = id.Sprite.HUD_COMBAT_BTN_BIN_OVER },
}

Sprites.SPRITE_BUTTON_NAMES = {
    "MENU", "FILTER", "INFO", "SETTINGS", "PAUSE", "STOP", "PLAY", "UNDO","REFRESH",
    "BACK", "PIN", "ERASER", "CROSS", "AUDIO", "PENCIL", "EYE","HIDE", "STAR",
    "LIST_LAYOUT", "GRID_LAYOUT", "CAPE", "SHIELD", "BODY", "AMULET", "LEGS",
    "BOOT", "OUTFIT", "HAND", "KEEPSAKE", "PYRAMID", "SPECIAL", "PLUS", "GRAPH",
    "IMPORT", "EXPORT", "LADDER_UP", "LADDER_DOWN", "ARROW_UP", "ARROW_RIGHT",
    "ARROW_LEFT", "ARROW_DOWN","SEARCH","CHAT","DIAMOND","SWAP","BROADCAST",
    "LOCK", "TRASH"
}

return Sprites
